name: C++ CI

# Executar o fluxo de trabalho em pushes e pull requests para a branch main
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build_and_test:
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Cache build directory
              id: cache-build
              uses: actions/cache@v4
              with:
                  path: build
                  key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-build-
            - name: Build project
              id: build-project
              run: |
                  mkdir -p build
                  cd build
                  cmake ..
                  cmake --build . --parallel
                    restore-keys: |
                        ${{ runner.os }}-build-
            - name: Build project
              run: |
                  mkdir -p build
                  cd build
                  cmake ..
                  cmake --build . --parallel

            - name: Set up C++ environment
              uses: aminya/setup-cpp@v1.7.1
              with:
                 compiler: gcc


            - name: Run tests
              run: |
                  cd build
                  ./bin/simulador ../data/first_test 
            - name: Upload artifact
              # v4.3.1 (latest as of June 2024)
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifact
                  path: build/bin/